services:
  - type: web
    name: gcc-stat-mart-dash
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dash_app:server
    healthCheckPath: /
